fix(ci): Fixed CI workflow Flutter Version
Fixed CI workflow Flutter Version and possible linting issues.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -7,3 +7,11 @@ if [ $STATUS -ne 0 ]; then
   echo "🚫 dart format failed. Aborting commit."
   exit $STATUS
 fi
+
+echo "⚙️ Running lints..."
+flutter analyze .
+STATUS=$?
+if [ $STATUS -ne 0 ]; then
+  echo "🚫 flutter analyze failed. Aborting commit."
+  exit $STATUS
+fi
